### recuperar las peliculas

GET http://localhost:1234/movies

### Peliculas por Id
GET http://localhost:1234/movies/b470068c-b3d1-4ead-9df4-a55d97a4f8c4

###Peliculas por genero
GET http://localhost:1234/movies?genre=acTion

###Create a new movie
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Godfather 4",
  "year": 1985,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}
###Actualizar una movie

PATCH http://localhost:1234/movies/b470068c-b3d1-4ead-9df4-a55d97a4f8c4
Content-Type: application/json

{
  "year": 1986
}

###Delete a movie
DELETE http://localhost:1234/movies/b470068c-b3d1-4ead-9df4-a55d97a4f8c4